
debug: true
log_level: DEBUG,sled=INFO,actix_web=WARN

service:
  host: 127.0.0.1
  port: 6333
  grpc_port: 6334


storage:
  performance:
    # Number of parallel threads used for search operations. If 0 - auto selection.
    max_search_threads: 4

  optimizers:
    # Minimum interval between forced flushes.
    flush_interval_sec: 1
